# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfoFlow' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for InfoFlow

  target 'InfoFlowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfoFlowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

	pod "MWPhotoBrowser"
    pod "TZImagePickerController"
    pod "FSTextView"
    pod "MJRefresh"
end
